version: 2
jobs:
  test:
    docker:
    - image: astronomerio/alpine-librdkafka-golang:1.9-0.11.0-r0
    working_directory: /go/src/github.com/astronomerio/clickstream-ingestion-api
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    machine: true
    working_directory: ~/go/src/github.com/astronomerio/clickstream-ingestion-api
    requires:
      - test
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run: VERSION=$CIRCLE_TAG make build-image
  release:
    machine: true
    working_directory: ~/go/src/github.com/astronomerio/clickstream-ingestion-api
    requires:
      - test
      - build
    steps:
      - checkout
      - run: VERSION=$CIRCLE_TAG make push-image
workflows:
  version: 2
  test-n-release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
           - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - release:
          requires:
           - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/