version: 2
jobs:
  test:
    docker:
    - image: astronomerio/alpine-librdkafka-golang:1.9-0.11.0-r0
    working_directory: /go/src/github.com/astronomerio/clickstream-ingestion-api
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    requires:
      - test
    steps:
      - setup_remote_docker
      - run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS 
        VERSION=$CIRCLE_TAG make build-image
  push:
    requires:
      - test
      - build
    steps:
      - run: |
        VERSION=$CIRCLE_TAG make push-image
      
workflows:
  version: 2
  test:
    jobs:
      - test
  release:
    jobs:
      - test
      - build
      - push
      filters:
        tags:
          only: /.*/
    